### ISSUE TITLE
Could you show you arch of this projects?

### ISSUE THREAD

**Issue by GingerNg** [paulpierre/RasaGPT#3]
I read your code, can't find what rasa do except connecting to telegram. Is it necessary?
Tks

**Comment by LuisGalo15** [comment]
I have the same question. Another thing I don't get is where you train the model. I found the app/api/models.py file, but I think that's a DB model, not the model trained or to train model.

**Comment by paulpierre** [comment]
@GingerNg - this audience for this project are users [Rasa](https://rasa.com/). It has support for intents, stories, etc. The goal was to provide a reference implementation on how to extend it to LLMs in a meaningful with a document retrieval pipeline built-in which was my original use-case. I agree, it is not necessary. In fact, someone should build a Rasa only for LLMs ;)

@LuisGalo15  - see above. the model training happens in in the directory `app/rasa/data` ... you have to setup your [NLU pipeline](https://rasa.com/docs/rasa/tuning-your-model/) via the yaml files. There is support for BERT, GPT-2, etc. to help handle intents. to run training epochs  via make, run `make rasa-train` This particular topic is beyond the scope of this project but LLMs are a fallback on purpose.
