### ISSUE TITLE
Installation stuck at Building api

### ISSUE THREAD

**Issue by aolin118** [paulpierre/RasaGPT#64]
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Building api
[+] Building 1077.8s (7/8)                                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                                         0.0s
 => => transferring dockerfile: 37B                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                            0.0s
 => => transferring context: 34B                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/python:3.9                                                                                                               15.4s
 => [1/4] FROM docker.io/library/python:3.9@sha256:c0dcc146710fed0a6d62cb55b92f00bfbfc3b931fff6218f4958bab58333c37b                                                          0.0s
 => [internal] load build context                                                                                                                                            0.0s
 => => transferring context: 1.46kB                                                                                                                                          0.0s
 => CACHED [2/4] WORKDIR /app/api                                                                                                                                            0.0s
 => CACHED [3/4] COPY . .                                                                                                                                                    0.0s
 => [4/4] RUN pip install --no-cache-dir -r requirements.txt                                                                                                              1062.4s
 => => #   Downloading numpy-1.26.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)                                                                           
 => => # INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, yo
 => => # u can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking                                        
 => => #   Downloading numpy-1.25.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)                                                                           
 => => #   Downloading numpy-1.25.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.7 MB)                                                                           
 => => #   Downloading numpy-1.25.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.7 MB)    

SEVERAL HOURS PASSED STILL STUCK AT THIS ENDLESS DOWNLOADING

**Comment by 34127chi** [comment]
1）maybe try some other pip source.
2）upgrade pip package.
3）specify package version
